
services:

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - barber
    restart: unless-stopped

  backend:
    image: node:lts-alpine
    # container_name: backend
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
    - "3000:3000"
    restart: unless-stopped
    networks:
      - barber
    depends_on:
      - postgres
    
  frontend:
    image: node:lts-alpine
    container_name: frontend
    working_dir: /app
    command: sh -c "npm install && npx ng serve --host 0.0.0.0"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - barber
    depends_on:
      - backend


networks:
  barber:
    driver: bridge

volumes:
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './postgres'
  backend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './backend'
  frontend:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './frontend'